server:
  port: 8020
spring:
  application:
    name: user-service
feign:
  hystrix:
    enabled: true
#客户访问网关的熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#网关请求服务的熔断
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 10000
